const INIT = 'INIT'
const UPDATE = 'UPDATE'

const OPEN_NEW_NOTE_FORM = 'OPEN_NEW_NOTE_FORM'

const OPEN_ARCHIVE = 'OPEN_ARCHIVE'
const DELETE_ALL = 'DELETE_ALL'

const CREATE_NOTE = 'CREATE_NOTE'
const EDIT_NOTE_STATUS = 'EDIT_NOTE_STATUS'
const UPDATE_NOTE = 'UPDATE_NOTE'
const DELETE_NOTE = 'DELETE_NOTE'
const ARCHIVE_NOTE = 'ARCHIVE_NOTE'
const UNZIP_NOTE = 'UNZIP_NOTE'

export {
  INIT,
  UPDATE,
  OPEN_NEW_NOTE_FORM,
  OPEN_ARCHIVE,
  DELETE_ALL,
  CREATE_NOTE,
  EDIT_NOTE_STATUS,
  UPDATE_NOTE,
  DELETE_NOTE,
  ARCHIVE_NOTE,
  UNZIP_NOTE
}